// svelte/src/App.svelte
<script lang="ts">
  import { loadLocale } from 'wuchale/load-utils'
  import './locales/main.loader.svelte.js'
  import Counter from './lib/Counter.svelte'

  let locale = $state('en')
    
</script>

{#await loadLocale(locale)}
  <!-- @wc-ignore -->
  Loading translations...
{:then}
  <main>
    <button onclick={() => {locale = locale === 'en' ? 'es' : 'en'}}>Current locale: {locale}</button>
    <h1>Vite + Svelte</h1>
  
    <div class="card">
      <Counter />
    </div>
  
    <p>
      Check out <a href="https://github.com/sveltejs/kit#readme" target="_blank" rel="noreferrer">SvelteKit</a>, the official Svelte app framework powered by Vite!
    </p>
  
    <p class="read-the-docs">
      Click on the Vite and Svelte logos to learn more
    </p>
  </main>
  
  <style>
    .logo {
      height: 6em;
      padding: 1.5em;
      will-change: filter;
      transition: filter 300ms;
    }
    .logo:hover {
      filter: drop-shadow(0 0 2em #646cffaa);
    }
    .logo.svelte:hover {
      filter: drop-shadow(0 0 2em #ff3e00aa);
    }
    .read-the-docs {
      color: #888;
    }
  </style>
{/await}

// react/src/App.tsx
'use client'
import { useEffect, useState } from 'react'
import './App.css'
import './locales/main.loader.js'
import { loadLocale } from 'wuchale/load-utils'
import Counter from './Counter'

function App() {
    const [locale, setLocale] = useState('en')
    const [loaded, setLoaded] = useState(false)

    useEffect(() => {
        setLoaded(false)
        loadLocale(locale).then(() => setLoaded(true))
    }, [locale])

    if (!loaded) {
        // @wc-ignore
        return 'Loading locale...'
    }

    return (
        <>
            <button onClick={() => setLocale(locale => locale === 'en' ? 'es' : 'en')}>{locale}</button>
            <h1>Vite + React</h1>
            <div className="card">
                <Counter />
                <p>
                    Edit <code>src/App.tsx</code> and save to test HMR
                </p>
            </div>
            <p className="read-the-docs">
                Click on the Vite and React logos to learn more
            </p>
        </>
    )
}

export default App
