// react/src/App.tsx
'use client'
import { useEffect, useState } from 'react'
import './App.css'
import './locales/main.loader.js'
import { loadLocale } from 'wuchale/load-utils'
import Counter from './Counter'

function App() {
    const [locale, setLocale] = useState('en')
    const [loaded, setLoaded] = useState(false)

    useEffect(() => {
        setLoaded(false)
        loadLocale(locale).then(() => setLoaded(true))
    }, [locale])

    if (!loaded) {
        // @wc-ignore
        return 'Loading locale...'
    }

    return (
        <>
            <button onClick={() => setLocale(locale => locale === 'en' ? 'es' : 'en')}>{locale}</button>
            <h1>Vite + React</h1>
            <div className="card">
                <Counter />
                <p>
                    Edit <code>src/App.tsx</code> and save to test HMR
                </p>
            </div>
            <p className="read-the-docs">
                Click on the Vite and React logos to learn more
            </p>
        </>
    )
}

export default App

// solidjs/src/App.tsx
import { createEffect, createSignal, Show, type Component } from 'solid-js';
import { loadLocale } from 'wuchale/load-utils'
import './locales/main.loader.js' // so that the loader is registered
import Counter from './Counter.jsx'

import styles from './App.module.css';

const App: Component = () => {
    const [locale, setLocale] = createSignal('en')
    const [loaded, setLoaded] = createSignal(false)
    createEffect(() => {
        setLoaded(false)
        loadLocale(locale()).then(() => setLoaded(true))
    })
    return (
        <div class={styles.App}>
            <Show when={loaded()} fallback={/* @wc-ignore */ 'Loading catalog...'}>
                <header class={styles.header}>
                    <button onClick={() => setLocale(locale() === 'en' ? 'es' : 'en')}>{locale()}</button>
                    <Counter />
                    <p>
                        Edit <code>src/App.tsx</code> and save to reload.
                    </p>
                    <a
                        class={styles.link}
                        href="https://github.com/solidjs/solid"
                        target="_blank"
                        rel="noopener noreferrer"
                    >
                        Learn Solid
                    </a>
                </header>
            </Show>
        </div>
    );
};

export default App;
